name: The Way
favicon: null
layout_spectrum: 0.32664415426552296
typography_spectrum: 0.6614669822156429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8262489624321461
  lightness: 0.21722363261505961
  saturation: 0.2879263758659363
  rhythmicContrast: 0.18784420401789248
purpose: []
