name: The Way
favicon: null
layout_spectrum: 0.94495
typography_spectrum: 0.6614669822156429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#afc4e1'
    - '#77726e'
    - '#4f5666'
  brandStrength: 0.8262489624321461
  lightness: 0.21722363261505961
  saturation: 0.125
  rhythmicContrast: 0.18784420401789248
purpose: []
